//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phirSOFT.Applications.FinancePlanner {
    using RibbonLib;
    using RibbonLib.Controls;
    
    public partial class Form1 {

        private void InitializeRibbon()
        {
        }

        private void LocalizeRibbon() {
            Ribbon.ConnectButton.Label = SR.Connect;
            Ribbon.ConnectToDropDownButton.Label = SR.ConnectTo;
            Ribbon.MainTab.Label = SR.Main;
            Ribbon.MainTab.Keytip = SR.KeytipMain;
            Ribbon.ConnectionGroup.Label = SR.Connection;
            Ribbon.DisconnectButton.Label = SR.Disconect;
            Ribbon.ReconnectButton.Label = SR.Reconect;
            Ribbon.WindowsTab.Label = SR.Windows;
            Ribbon.CategoryEditorButton.Label = SR.CategoryEditor;
            Ribbon.LogButton.Label = SR.Log;
            Ribbon.TransactionOverviewButton.Label = SR.TransactionOverview;
            Ribbon.ReminderButton.Label = SR.Reminder;
            Ribbon.SearchButton.Label = SR.Search;
            Ribbon.TransactionEditorButton.Label = SR.TransactionEditor;
            Ribbon.AnnualReportButton.Label = SR.AnualReport;
            Ribbon.CategoriesToolsTabGroup.Label = SR.CategoriesTools;
            Ribbon.CategoriesTab.Label = SR.Categories;
            Ribbon.EditCategoryGroup.Label = SR.Edit;
            Ribbon.AddButton.Label = SR.Add;
            Ribbon.AddButton.LabelDescription = SR.AddDescription;
            Ribbon.AddButton.TooltipTitle = SR.AddTitle;
            Ribbon.AddButton.TooltipDescription = SR.AddTooltipDescription;
            Ribbon.DeleteButton.Label = SR.Delete;
            Ribbon.DeleteButton.LabelDescription = SR.DeleteDescription;
            Ribbon.DeleteButton.TooltipTitle = SR.DeleteTitle;
            Ribbon.DeleteButton.TooltipDescription = SR.DeleteTooltipDescription;
            Ribbon.EditButton.Label = SR.Edit;
            Ribbon.EditButton.LabelDescription = SR.EditDescription;
            Ribbon.EditButton.TooltipTitle = SR.EditTitle;
            Ribbon.EditButton.TooltipDescription = SR.EditTooltipDescription;
            Ribbon.MoveButton.Label = SR.Move;
            Ribbon.MoveButton.LabelDescription = SR.MoveDescription;
            Ribbon.MoveButton.TooltipTitle = SR.MoveTitle;
            Ribbon.MoveButton.TooltipDescription = SR.MoveTooltipDescription;
            Ribbon.JoinButton.Label = SR.Join;
            Ribbon.JoinButton.LabelDescription = SR.JoinDescription;
            Ribbon.JoinButton.TooltipTitle = SR.JoinTitle;
            Ribbon.JoinButton.TooltipDescription = SR.JoinTooltipDescription;
            Ribbon.ChangeCategoryGroup.Label = SR.Changes;
            Ribbon.AcceptButton.Label = SR.Accept;
            Ribbon.AcceptButton.LabelDescription = SR.AcceptDescription;
            Ribbon.AcceptButton.TooltipTitle = SR.AcceptTitle;
            Ribbon.AcceptButton.TooltipDescription = SR.AcceptTooltipDescription;
            Ribbon.DiscardButton.Label = SR.Discard;
            Ribbon.DiscardButton.LabelDescription = SR.DiscardDescription;
            Ribbon.DiscardButton.TooltipTitle = SR.DiscardTitle;
            Ribbon.DiscardButton.TooltipDescription = SR.DiscardTooltipDescription;
        }
    }
}
